(defun operacao(a operador b)
    (if (eq operador '+)
        (+ a b)
        (if (eq operador '-)
            (- a b)
            (if (eq operador '*)
                (* a b)
                (if (eq operador '/)
                    (/ a b)
                    0
                )
            )
        )
    )
)

(defun main()
    (setq a (read))
    (setq operador (read))
    (setq b (read))
    (write-line(write-to-string (operacao a operador b )))
)

(main)